<?xml version="1.0" encoding="UTF-8"?>
<project name="test.c">
  <tokens>
    <token>
      <number>1</number>
      <value>int</value>
      <type>keyword</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_INT</mimetype>
    </token>
    <token>
      <number>2</number>
      <value>main</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>3</number>
      <value>(</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_LP</mimetype>
    </token>
    <token>
      <number>4</number>
      <value>int</value>
      <type>keyword</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_INT</mimetype>
    </token>
    <token>
      <number>5</number>
      <value>a</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>6</number>
      <value>,</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_COMMA</mimetype>
    </token>
    <token>
      <number>7</number>
      <value>int</value>
      <type>keyword</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_INT</mimetype>
    </token>
    <token>
      <number>8</number>
      <value>b</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>9</number>
      <value>)</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_RP</mimetype>
    </token>
    <token>
      <number>10</number>
      <value>{</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_LB</mimetype>
    </token>
    <token>
      <number>11</number>
      <value>a</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>12</number>
      <value>=</value>
      <type>operator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ASIGN</mimetype>
    </token>
    <token>
      <number>13</number>
      <value>2</value>
      <type>const_i</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_CONSTI</mimetype>
    </token>
    <token>
      <number>14</number>
      <value>;</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_SEMI</mimetype>
    </token>
    <token>
      <number>15</number>
      <value>while</value>
      <type>keyword</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_WHILE</mimetype>
    </token>
    <token>
      <number>16</number>
      <value>(</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_LP</mimetype>
    </token>
    <token>
      <number>17</number>
      <value>a</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>18</number>
      <value>&gt;</value>
      <type>operator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_G</mimetype>
    </token>
    <token>
      <number>19</number>
      <value>b</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>20</number>
      <value>)</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_RP</mimetype>
    </token>
    <token>
      <number>21</number>
      <value>{</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_LB</mimetype>
    </token>
    <token>
      <number>22</number>
      <value>b</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>23</number>
      <value>=</value>
      <type>operator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ASIGN</mimetype>
    </token>
    <token>
      <number>24</number>
      <value>b</value>
      <type>identifier</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ID</mimetype>
    </token>
    <token>
      <number>25</number>
      <value>+</value>
      <type>operator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_ADD</mimetype>
    </token>
    <token>
      <number>26</number>
      <value>1</value>
      <type>const_i</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_CONSTI</mimetype>
    </token>
    <token>
      <number>27</number>
      <value>;</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_SEMI</mimetype>
    </token>
    <token>
      <number>28</number>
      <value>}</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_RB</mimetype>
    </token>
    <token>
      <number>29</number>
      <value>}</value>
      <type>separator</type>
      <line>1</line>
      <valid>true</valid>
      <mimetype>TKN_RB</mimetype>
    </token>
  </tokens>
</project>

